language: node_js

node_js:
  - 12
  - 10
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm test
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
